-- Initial schema for cert-alert.
-- Written in portable SQL so the same migration runs on H2 (dev/test) and PostgreSQL.

CREATE TABLE certificate_target (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    hostname            VARCHAR(255) NOT NULL,
    port                INTEGER NOT NULL DEFAULT 443,
    description         VARCHAR(1000),
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    last_status         VARCHAR(32),
    last_checked_at     TIMESTAMP WITH TIME ZONE,
    last_expires_at     TIMESTAMP WITH TIME ZONE,
    last_alerted_at     TIMESTAMP WITH TIME ZONE,
    last_alerted_status VARCHAR(32),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_certificate_target_name UNIQUE (name)
);

CREATE TABLE certificate_check (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id         BIGINT NOT NULL,
    status            VARCHAR(32) NOT NULL,
    checked_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    subject           VARCHAR(500),
    issuer            VARCHAR(500),
    serial_number     VARCHAR(100),
    not_before        TIMESTAMP WITH TIME ZONE,
    not_after         TIMESTAMP WITH TIME ZONE,
    days_until_expiry BIGINT,
    error_message     VARCHAR(1000),
    CONSTRAINT fk_certificate_check_target FOREIGN KEY (target_id)
        REFERENCES certificate_target (id) ON DELETE CASCADE
);

CREATE INDEX idx_certificate_check_target ON certificate_check (target_id);
CREATE INDEX idx_certificate_check_checked_at ON certificate_check (checked_at);
