-- Initial schema for cert-alert.
-- Portable SQL so the same migration runs on H2 (dev/test) and PostgreSQL.
--
-- Two primary object types are scraped from the directory: users and servers. Each holds
-- cached certificate details, plus denormalised roll-up columns the search tables filter
-- and sort on.

CREATE TABLE directory_user (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dn                  VARCHAR(512) NOT NULL,
    uid                 VARCHAR(255),
    common_name         VARCHAR(255),
    display_name        VARCHAR(255),
    given_name          VARCHAR(255),
    surname             VARCHAR(255),
    email               VARCHAR(320),
    telephone_number    VARCHAR(64),
    title               VARCHAR(255),
    employee_type       VARCHAR(128),
    country             VARCHAR(128),
    organization        VARCHAR(255),
    organizational_unit VARCHAR(255),
    certificate_count   INTEGER NOT NULL DEFAULT 0,
    certificate_status  VARCHAR(32) NOT NULL DEFAULT 'NONE',
    earliest_expiry     TIMESTAMP WITH TIME ZONE,
    latest_expiry       TIMESTAMP WITH TIME ZONE,
    first_seen_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    last_synced_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_directory_user_dn UNIQUE (dn)
);

CREATE INDEX idx_directory_user_email ON directory_user (email);
CREATE INDEX idx_directory_user_uid ON directory_user (uid);
CREATE INDEX idx_directory_user_cert_status ON directory_user (certificate_status);
CREATE INDEX idx_directory_user_earliest_expiry ON directory_user (earliest_expiry);

CREATE TABLE directory_server (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dn                  VARCHAR(512) NOT NULL,
    common_name         VARCHAR(255),
    fqdn                VARCHAR(255),
    description         VARCHAR(1000),
    serial_number       VARCHAR(128),
    operating_system    VARCHAR(255),
    server_poc_display  VARCHAR(2000),
    organization        VARCHAR(255),
    organizational_unit VARCHAR(255),
    certificate_count   INTEGER NOT NULL DEFAULT 0,
    certificate_status  VARCHAR(32) NOT NULL DEFAULT 'NONE',
    earliest_expiry     TIMESTAMP WITH TIME ZONE,
    latest_expiry       TIMESTAMP WITH TIME ZONE,
    first_seen_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    last_synced_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_directory_server_dn UNIQUE (dn)
);

CREATE INDEX idx_directory_server_cn ON directory_server (common_name);
CREATE INDEX idx_directory_server_fqdn ON directory_server (fqdn);
CREATE INDEX idx_directory_server_cert_status ON directory_server (certificate_status);
CREATE INDEX idx_directory_server_earliest_expiry ON directory_server (earliest_expiry);

-- serverPoc is multi-valued in the directory. Held separately so "servers this person is
-- responsible for" is an indexed join against directory_user.email.
CREATE TABLE directory_server_poc (
    server_id BIGINT NOT NULL,
    poc_email VARCHAR(320) NOT NULL,
    CONSTRAINT fk_server_poc_server FOREIGN KEY (server_id)
        REFERENCES directory_server (id) ON DELETE CASCADE
);

CREATE INDEX idx_server_poc_email ON directory_server_poc (poc_email);

CREATE TABLE cached_certificate (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT,
    server_id                 BIGINT,
    sha256_fingerprint        VARCHAR(64) NOT NULL,
    serial_number             VARCHAR(100),
    subject_dn                VARCHAR(1000),
    issuer_dn                 VARCHAR(1000),
    not_before                TIMESTAMP WITH TIME ZONE,
    not_after                 TIMESTAMP WITH TIME ZONE,
    signature_algorithm       VARCHAR(100),
    key_algorithm             VARCHAR(50),
    key_size                  INTEGER,
    subject_alternative_names VARCHAR(2000),
    status                    VARCHAR(32) NOT NULL DEFAULT 'VALID',
    cached_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_cached_certificate_user FOREIGN KEY (user_id)
        REFERENCES directory_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_cached_certificate_server FOREIGN KEY (server_id)
        REFERENCES directory_server (id) ON DELETE CASCADE,
    -- A certificate hangs off exactly one owner, never both and never neither.
    CONSTRAINT ck_cached_certificate_owner CHECK (
        (user_id IS NOT NULL AND server_id IS NULL)
        OR (user_id IS NULL AND server_id IS NOT NULL)
    )
);

CREATE INDEX idx_cached_certificate_user ON cached_certificate (user_id);
CREATE INDEX idx_cached_certificate_server ON cached_certificate (server_id);
CREATE INDEX idx_cached_certificate_not_after ON cached_certificate (not_after);
CREATE INDEX idx_cached_certificate_status ON cached_certificate (status);
CREATE INDEX idx_cached_certificate_fingerprint ON cached_certificate (sha256_fingerprint);
